# Generated by Django 4.1.1 on 2022-10-06 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AliveMonster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_hp', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlvieMonsterInGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AlvieMonsterInStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.alivemonster')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('hp', models.IntegerField(default=100)),
                ('attack', models.IntegerField()),
                ('defence', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.game')),
                ('monsters', models.ManyToManyField(through='rpg.AlvieMonsterInStage', to='rpg.alivemonster')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=100)),
                ('attack', models.IntegerField(default=10)),
                ('defence', models.IntegerField(default=10)),
                ('name', models.CharField(max_length=64)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.hero'),
        ),
        migrations.AddField(
            model_name='game',
            name='monsters',
            field=models.ManyToManyField(through='rpg.AlvieMonsterInGame', to='rpg.alivemonster'),
        ),
        migrations.AddField(
            model_name='alviemonsterinstage',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.stage'),
        ),
        migrations.AddField(
            model_name='alviemonsteringame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.game'),
        ),
        migrations.AddField(
            model_name='alviemonsteringame',
            name='monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.alivemonster'),
        ),
        migrations.AddField(
            model_name='alivemonster',
            name='monster_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.monster'),
        ),
    ]
