# Generated by Django 4.1.1 on 2022-10-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0002_stage_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alviemonsteringame',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='alviemonsterinstage',
            name='amount',
        ),
    ]
