# Generated by Django 4.1.1 on 2022-10-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0003_remove_alviemonsteringame_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
